config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites', to: 'favorites#index'

  get 'movie_details/show'
  devise_for :users
  
  

  get '/search_results', to: 'movies#search_results', as: 'search_results'

  get 'search_movies', to: 'movies#search', as: 'search_movies'

  resources :movies do
   
   
    post 'create', on: :collection
  end
  resources :movies, only: [:index, :create, :destroy ]
  get 'movie_details/:id', to: 'movie_details#show', as: 'movie_details'
  get 'movies/favorites', to: 'movies#index', as: 'favorite_movies'

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :favorite_movies, class_name: 'Movie'
         has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    
    @favorite_movies = Movie.paginate(page: params[:page], per_page: 4) # Muestra 10 películas por página
  end
  
end

app/controllers/movie_details_controller.rb
class MovieDetailsController < ApplicationController
  def show
    movie_id = params[:id] 
    @movie = fetch_movie_details(movie_id)
    
    if @movie
      render 'show'
    else
      flash[:error] = "La película no se encontró."
      redirect_to movies_path
    end
  end
  def fetch_movie_details(movie_id)
    api_key = '4cdb0dbd3ea893e166f8a05fbade0aa4'
    url = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{api_key}&language=es-ES"
    
    response = RestClient.get(url)
    data = JSON.parse(response.body)
    
    data
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'rest-client'
  require 'json'

  before_action :authenticate_user!

  def index
    
    @favorite_movies = current_user.movies
    @movies = popular_movies
    
  end
  

  def create
    movie_params = {
      title: params[:movie][:title],
      year: params[:movie][:year],
      plot: params[:movie][:plot],
      poster_url: params[:movie][:poster_url],  
      user_id: current_user.id
    }

    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:success] = "Película guardada en tu lista de favoritos."
    else
      flash[:error] = "No se pudo guardar la película en tu lista de favoritos."
    end
    redirect_to movies_path
  end  

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      flash[:success] = "Película eliminada de tus favoritos."
    else
      flash[:error] = "No se pudo eliminar la película de tus favoritos."
    end
    redirect_to movies_path
    
  end

  def search
    @favorite_movies = current_user.movies
    @search_term = params[:search_term]
    @movies = popular_movies(@search_term)
    render 'search'
  end
  

  private

  def popular_movies(search_term = nil)
    api_key = '4cdb0dbd3ea893e166f8a05fbade0aa4'
    encoded_title = URI.encode_www_form_component(search_term)
    url = if encoded_title.present?
            "https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&query=#{encoded_title}&language=es-ES"
          else
            "https://api.themoviedb.org/3/movie/popular?api_key=#{api_key}&language=es-ES"
          end

    response = RestClient.get(url)
    data = JSON.parse(response.body)

    if data['results']
      data['results']
    else
      []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movie_details_helper.rb
module MovieDetailsHelper
end

app/helpers/movies_details_helper.rb
module MoviesDetailsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/favorites/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Películas Favoritas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .movie-card {
      border: 1px solid #ddd;
      padding: 5px;
      margin: 10px;
      background-color: #f9f9f9;
      border-radius: 8px;
      text-align: center;
    }

    .movie-card img {
      max-width: 100%;
      height: auto;
    }

    .movie-card h5 {
      margin-top: 10px;
      font-weight: bold;
      font-size: 16px;
    }

    .movie-card p {
      font-size: 14px;
    }

    .no-favorites {
      font-size: 18px;
      text-align: center;
      margin-top: 20px;
    }

    .delete-button {
      margin-top: 10px;
    }
  </style>
</head>
<%= render "shared/nav" %>
<body>
  <div class="container">
    <h1 class="mt-5 text-center">Películas Favoritas</h1>

    <% if @favorite_movies.any? %>
      <div class="row mt-3">
        <% @favorite_movies.each do |movie| %>
          <div class="col-md-3">
            <div class="movie-card">
              <% if movie.poster_url.present? && movie.poster_url != "N/A" %>
                <%= image_tag movie.poster_url, alt: movie.title %>
              <% else %>
                <%= image_tag "https://via.placeholder.com/150", alt: movie.title %>
              <% end %>
              <h5><strong><%= movie.title %></strong></h5>
              <p>(Año: <%= movie.year %>)</p>
              <%= form_for movie, url: movie_path(movie), method: :delete, remote: true do |f| %>
                <%= f.submit "Eliminar", class: "btn btn-danger btn-sm delete-button" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="no-favorites">No tienes ninguna película favorita aún. ¡Busca y agrega algunas!</p>
    <% end %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiPe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie_details/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Detalles de la Película</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <style>
    /* Estilos generales */
    body {
      font-family: Arial, sans-serif;
      background-color: #f7f7f7;
    }

    .container {
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      padding: 20px;
      margin-top: 20px;
    }

    h1 {
      font-size: 36px;
      color: #007BFF;
      text-align: center;
    }

    /* Estilos de la película */
    .movie-details {
      display: flex;
      flex-direction: column;
      border: 1px solid #007BFF;
      background-color: #ffffff;
      border-radius: 10px;
      padding: 20px;
      margin: 20px 0;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }

    .movie-images {
      display: flex;
      justify-content: center;
    }

    .movie-images img {
      max-width: 300px;
      height: auto;
      margin: 10px;
      border: 1px solid #007BFF;
      border-radius: 10px;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    }

    .movie-info {
      margin-top: 20px;
    }

    .movie-details h3 {
      font-size: 32px;
      color: #007BFF;
      margin: 0;
    }

    .movie-details p {
      font-size: 18px;
      margin-bottom: 15px;
    }

    .fa {
      margin-right: 5px;
      color: #007BFF;
    }
  </style>
</head>
<body>
  <!-- Incluimos la navegación compartida -->
  <%= render "shared/nav" %>

  <div class="container">
    <h1 class="mt-5">Detalles de la Película</h1>
    <div class="movie-details">
      <!-- Agregamos un div para las imágenes -->
      <div class="movie-images">
        <% if @movie['backdrop_path'].present? && @movie['backdrop_path'] != "N/A" %>
          <%= image_tag "https://image.tmdb.org/t/p/w500#{@movie['backdrop_path']}", alt: @movie['title'], class: "img-thumbnail" %>
        <% end %>
        <% if @movie['backdrop_path'].present? && @movie['backdrop_path'] != "N/A" %>
          <%= image_tag "https://image.tmdb.org/t/p/w500#{@movie['backdrop_path']}", alt: @movie['title'], class: "img-thumbnail" %>
        <% end %>
        <!-- Puedes agregar más imágenes aquí -->
      </div>
      <div class="movie-info">
        <h3><i class="fas fa-film"></i><strong><%= @movie['title'] %></strong></h3>
        <p><i class="fas fa-calendar-alt"></i><strong>Año de lanzamiento:</strong> <%= @movie['release_date'] %></p>
        <p><i class="fas fa-info-circle"></i><strong>Descripción:</strong> <%= @movie['overview'] %></p>
        <p><i class="fas fa-star"></i><strong>Calificación:</strong> <%= @movie['vote_average'] %></p>
        <p><i class="fas fa-language"></i><strong>Idioma original:</strong> <%= @movie['original_language'] %></p>
        <p><i class="fas fa-dollar-sign"></i><strong>Presupuesto:</strong> $<%= @movie['budget'] %></p>
        <p><i class="fas fa-money-bill-wave"></i><strong>Ingresos:</strong> $<%= @movie['revenue'] %></p>
        <p><i class="fas fa-clock"></i><strong>Duración:</strong> <%= @movie['runtime'] %> minutos</p>
        <p><i class="fas fa-tag"></i><strong>Tagline:</strong> <%= @movie['tagline'] %></p>
        <p><i class="fas fa-tags"></i><strong>Géneros:</strong>
          <% if @movie['genres'].present? %>
            <ul>
              <% @movie['genres'].each do |genre| %>
                <li><%= genre['name'] %></li>
              <% end %>
            </ul>
          <% else %>
            No disponible
          <% end %>
        </p>
        <p><i class="fas fa-building"></i><strong>Compañías de producción:</strong>
          <% if @movie['production_companies'].present? %>
            <ul>
              <% @movie['production_companies'].each do |company| %>
                <li><%= company['name'] %> (<%= company['origin_country'] %>)</li>
              <% end %>
            </ul>
          <% else %>
            No disponible
          <% end %>
        </p>
        <p><i class="fas fa-globe"></i><strong>Países de producción:</strong>
          <% if @movie['production_countries'].present? %>
            <ul>
              <% @movie['production_countries'].each do |country| %>
                <li><%= country['name'] %> (<%= country['iso_3166_1'] %>)</li>
              <% end %>
            </ul>
          <% else %>
            No disponible
          <% end %>
        </p>
        <p><i class="fas fa-volume-up"></i><strong>Idiomas hablados:</strong>
          <% if @movie['spoken_languages'].present? %>
            <ul>
              <% @movie['spoken_languages'].each do |language| %>
                <li><%= language['name'] %> (<%= language['iso_639_1'] %>)</li>
              <% end %>
            </ul>
          <% else %>
            No disponible
          <% end %>
        </p>
        <p><i class="fas fa-check-circle"></i><strong>Estado:</strong> <%= @movie['status'] %></p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/movies/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Películas Favoritas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .movie-card {
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
      border: 1px solid #ccc;
      margin: 10px;
      padding: 10px;
      cursor: pointer;
      transition: transform 0.2s;
      max-width: 250px;
      background-color: #f9f9f9;
      border-radius: 8px;
    }

    .movie-card img {
      max-width: 200px;
      height: auto;
    }

    .movie-card:hover {
      transform: scale(1.05);
    }

    .movie-card h5 {
      margin-bottom: 0;
    }

    .search-form {
      margin-top: 20px;
    }
      .movie-card p {
    max-height: 100px; /* Altura máxima para la descripción */
    overflow: hidden;  /* Ocultar el exceso de texto */
    text-overflow: ellipsis; /* Agregar puntos suspensivos al final del texto truncado */
  }

    .alert {
      margin-top: 20px;
    }
  </style>
</head>
 <%= render "shared/nav" %>
<body>

  <div class="container">

 


    <%= render "shared/search_form" %>

    <% if flash[:success].present? %>
      <div class="alert alert-success text-center">
        <%= flash[:success] %>
      </div>
    <% elsif flash[:error].present? %>
      <div class="alert alert-danger text-center">
        <%= flash[:error] %>
      </div>
    <% end %>

    <% if @movies.present? %>
      <h2 class="mt-4 text-center">Películas</h2>
      <div class="row mt-3 justify-content-center">
        <% @movies.each do |movie| %>
          <div class="col-md-4">
            <div class="movie-card">
              <% if movie['poster_path'].present? && movie['poster_path'] != "N/A" %>
                <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'], class: "img-thumbnail" %>
              <% else %>
                <p>No hay póster disponible</p>
              <% end %>
              <div class="mt-2">
                <h5><strong><%= movie['title'] %></strong></h5>
                <p>(Año: <%= movie['release_date'].to_s.split('-').first %>)</p>
                <p><%= movie['overview'] %></p>
                <% if current_user %>
                  <%= form_tag(movies_path, method: :post) do %>
                    <%= hidden_field_tag 'movie[title]', movie['title'] %>
                    <%= hidden_field_tag 'movie[year]', movie['release_date'].to_s.split('-').first %>
                    <%= hidden_field_tag 'movie[plot]', movie['overview'] %>
                    <%= hidden_field_tag 'movie[poster_url]', "https://image.tmdb.org/t/p/w500#{movie['poster_path']}" %>
                    <%= submit_tag "Agregar a Favoritos", class: "btn btn-success btn-sm mt-2" %>
                    <a href="<%= movie_details_path(movie['id']) %>" class="btn btn-success btn-sm mt-2">Ver detalles</a>


                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</body>
</html>

app/views/movies/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .movie-card {
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
      border: 1px solid #ccc;
      margin: 10px;
      padding: 10px;
      cursor: pointer;
      transition: transform 0.2s;
      max-width: 250px;
      background-color: #f9f9f9;
      border-radius: 8px;
    }

    .movie-card img {
      max-width: 200px;
      height: auto;
    }

    .movie-card:hover {
      transform: scale(1.05);
    }

    .movie-card h5 {
      margin-bottom: 0;
    }

    .movie-card p {
      max-height: 100px;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .btn-success {
      background-color: #28a745; 
      border-color: #28a745;
    }
  </style>
</head>
<body>
<%= render "shared/nav" %>
  <div class="container">
    <h1 class="mt-5">Resultados de Búsqueda</h1>

    <% if @movies.present? %>
      <div class="row mt-3 justify-content-center">
        <% @movies.each do |movie| %>
          <div class="col-md-4">
            <div class="movie-card">
              <% if movie['poster_path'].present? && movie['poster_path'] != "N/A" %>
                <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'], class: "img-thumbnail" %>
              <% else %>
                <%= image_tag "https://via.placeholder.com/150", alt: movie['title'], class: "img-thumbnail" %>
              <% end %>
              <div class="mt-2">
                <h5><strong><%= movie['title'] %></strong></h5>
                <p>(Año: <%= movie['release_date'].to_s.split('-').first %>)</p>
                <p><%= movie['overview'] %></p>
                <% if current_user %>
                  <%= form_tag(movies_path, method: :post) do %>
                    <%= hidden_field_tag 'movie[title]', movie['title'] %>
                    <%= hidden_field_tag 'movie[year]', movie['release_date'].to_s.split('-').first %>
                    <%= hidden_field_tag 'movie[plot]', movie['overview'] %>
                    <%= hidden_field_tag 'movie[poster_url]', "https://image.tmdb.org/t/p/w500#{movie['poster_path']}" %>
                    <%= submit_tag "Agregar a Favoritos", class: "btn btn-success btn-sm mt-2" %>
                    <a href="<%= movie_details_path(movie['id']) %>" class="btn btn-success btn-sm mt-2">Ver detalles</a>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="mt-3 text-center">No se encontraron resultados para la búsqueda.</p>
    <% end %>
  </div>
</body>
</html>

app/views/shared/_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    /* Estilo del menú */
    .menu {
      background-color: #35367b;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px 20px;
    }

    /* Estilo del logo */
    .logo {
      
      font-weight: bold;
      height: 50px; /* Altura fija para la imagen */
      display: flex;
      align-items: center;
    }

    .logo img {
      height: 100%; 
    }

    .menu-options {
      list-style: none;
      padding: 0;
      margin: 0;
      display: flex;
    }

    .menu-option {
      margin-right: 20px;
    }

    .menu-option:last-child {
      margin-right: 0;
    }

    .menu-option a {
      text-decoration: none;
      color: white; /* Color del texto de las opciones del menú */
      font-weight: bold;
      font-size: 16px;
    }
  </style>
</head>
<body>
  <div class="menu">
    <div class="logo">
      <img src="../assets/LOGO.png" alt="">
    </div>
    <ul class="menu-options">
      <li class="menu-option"><a href="/">Inicio</a></li>
      <li class="menu-option"><a href="<%= favorites_path %>">Favoritas</a></li>
      <li class="menu-option">
          <%= link_to "Cerrar Sesión", destroy_user_session_path, class: ""%> 
      </li>

    </ul>
  </div>
</body>
</html>

app/views/shared/_search_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f0f0f0;
    }
    h2 {
      color: #333;
      text-align: center;
    }
    .search-container {
      text-align: center;
      margin: 50px auto;
      width: 50%;
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      padding: 20px;
    }
    .input-group {
      display: flex;
      justify-content: center;
    }
    .form-control {
      width: 70%;
      padding: 10px;
      border: 2px solid #333;
      border-radius: 5px;
      font-size: 16px;
    }
    .btn-primary {
      background-color: #007BFF;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      font-size: 16px;
      cursor: pointer;
    }
    .btn-primary:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <h2>Buscar Películas</h2>
  <div class="search-container">
    <form action="<%= search_movies_path %>" method="get">
      <div class="input-group mb-3">
        <input type="text" name="search_term" class="form-control" placeholder="Buscar películas...">
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
      </div>
    </form>
  </div>
</body>
</html>